[package]
name = "bomper"
version = "0.4.3"
edition = "2021"

[[bin]]
name = "bomper"
path = "src/main.rs"

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
figment = { version = "0.10.6", features = ["toml", "env"] }
memmap = "0.7.0"
rayon = "1.5.3"
regex = "1.6.0"
serde = { version = "1.0.140", features = ["derive"] }
tempfile = "3.3.0"
thiserror = "1.0.31"
