[package]
name = "bomper"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bomper"
path = "src/main.rs"

[dependencies]
figment = { version = "0.10.6", features = ["toml", "env"] }
memmap = "0.7.0"
serde = { version = "1.0.140", features = ["derive"] }
thiserror = "1.0.31"
