name: tag
on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Determine version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.get_version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: rrval/workflows/.github/workflows/rust_publish.yml@v1.0.0
        secrets:
            CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
